### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by talamortis** [talamortis/Tbc_issue_tracker#1]
## Resapwn Instances
- [ ] Hellfire Ramparts
- [ ] Blood Furnace
- [ ] Shattered Halls
- [ ] Auchenai Crypts
- [ ] Mana Tombs
- [ ] Sethekk Halls
- [ ] ShadowLabyrinth
- [ ] Slave Pens
- [ ] Steam Vault
- [ ] Underbog
- [ ] Mechanar
- [ ] Arcatraz
- [ ] Botanica
- [ ] Escape From Durn holde Keep
- [ ] The Black Morass

## Instance Waypoints
- [ ] Hellfire Ramparts
- [ ] Blood Furnace
- [ ] Shattered Halls
- [ ] Auchenai Crypts
- [ ] Mana Tombs
- [ ] Sethekk Halls
- [ ] ShadowLabyrinth
- [ ] Slave Pens
- [ ] Steam Vault
- [ ] Underbog
- [ ] Mechanar
- [ ] Arcatraz
- [ ] Botanica
- [ ] Escape From Durn holde Keep
- [ ] The Black Morass

## Issues
- [ ] Keli'dan the Berserker not returning to middle after evade
- [ ] Keli'dan the Berserker does not spawn creatures after wipe
